### ISSUE TITLE
works on centos, but not on windows

### ISSUE THREAD

**Issue by spyhunter99** [rubygems/rubygems-mirror#14]
C:\Ruby193\bin>gem mirror
Fetching: http://rubygems.org/specs.4.8.gz
ERROR:  While executing gem ... (Zlib::GzipFile::Error)
    unexpected end of file

C:\Ruby193\bin>gem list

**\* LOCAL GEMS ***

bigdecimal (1.1.0)
builder (3.0.0)
certified (0.1.0)
gzip (1.0)
http (0.2.0)
io-console (0.3)
json (1.5.4)
minitest (3.2.0, 2.5.1)
net-http-persistent (2.7)
persistent (0.1.0)
rake (0.9.2.2)
rdoc (3.12, 3.9.4)
rubygems-mirror (1.0.1)
Zliby (0.0.5)

**Comment by SuriyaaKudoIsc** [comment]
@luislavena Same issue on Windows 10:

```cmd
C:\Users\Suriyaa\Downloads>gem mirror --debug -V
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59 - cannot load such file -- net/http/pipeline
Fetching: https://rubygems.org/specs.4.8
Fetching: https://rubygems.org/prerelease_specs.4.8
Fetching: https://rubygems.org/latest_specs.4.8
Exception `Errno::EEXIST' at C:/Ruby/Ruby23-x64/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - H:/GEMINABOX/data
Exception `EOFError' at C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/util.rb:17 - end of file reached
Exception `Zlib::GzipFile::Error' at C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/util.rb:17 - unexpected end of file
ERROR:  While executing gem ... (Zlib::GzipFile::Error)
    unexpected end of file
        C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/util.rb:17:in `read'
        C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/util.rb:17:in `gunzip'
        C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems.rb:615:in `gunzip'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror.rb:37:in `block (2 levels) in update_specs'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror.rb:37:in `open'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror.rb:37:in `block in update_specs'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror.rb:32:in `each'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror.rb:32:in `update_specs'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror/command.rb:59:in `block in execute'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror/command.rb:39:in `each'
        C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubygems-mirror-1.1.0/lib/rubygems/mirror/command.rb:39:in `execute'
        C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/command.rb:310:in `invoke_with_build_args'
        C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:171:in `process_args'
        C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:141:in `run'
        C:/Ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/gem_runner.rb:59:in `run'
        C:/Ruby/Ruby23-x64/bin/gem:21:in `<main>'

C:\Users\Suriyaa\Downloads>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.1
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: C:/Users/Suriyaa/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: C:/Ruby/Ruby23-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby/Ruby23-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Suriyaa/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0
     - C:/Users/Suriyaa/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Python\Python35
     - C:\Program Files\nodejs\
     - C:\Ruby\Ruby23-x64\bin
     - C:\Ruby\RubyDevKit\bin

C:\Users\Suriyaa\Downloads>
```
