### ISSUE TITLE
Error - HTTP request path is empty

### ISSUE THREAD

**Issue by rsanheim** [rubygems/rubygems-mirror#54]
Just trying this out for a local gem mirror, and it errors out pretty early:

```
[~]> gem mirror -V --backtrace
Fetching: http://gems.rubyforge.org/specs.4.8
Fetching: http://gems.rubyforge.org/prerelease_specs.4.8
Fetching: http://gems.rubyforge.org/latest_specs.4.8
Error connecting to http://gems.rubyforge.org/specs.4.8.gz: HTTP request path is empty
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - /Users/rsanheim/.gem/mirror/specs.4.8.gz
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror.rb:36:in `read'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror.rb:36:in `block (2 levels) in update_specs'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror.rb:36:in `open'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror.rb:36:in `block in update_specs'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror.rb:31:in `each'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror.rb:31:in `update_specs'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror/command.rb:59:in `block in execute'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror/command.rb:39:in `each'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror/command.rb:39:in `execute'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/command.rb:313:in `invoke_with_build_args'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/command_manager.rb:173:in `process_args'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/command_manager.rb:143:in `run'
	/usr/local/var/rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/gem_runner.rb:59:in `run'
	/usr/local/var/rbenv/versions/2.5.5/bin/gem:21:in `<main>'
```

Here is my .mirrorrc:

```
---
- from: http://gems.rubyforge.org
  to: /Users/rsanheim/.gem/mirror
  parallelism: 2
  skiperror: true
```

**Comment by rsanheim** [comment]
Looks like `specs.4.8.gz` returns a 301 from Rubygems:

```
[~]> curl -I  http://gems.rubyforge.org/specs.4.8.gz
HTTP/1.1 301 Moved Permanently
Server: Varnish
Retry-After: 0
Content-Length: 0
Accept-Ranges: bytes
Date: Tue, 14 May 2019 15:01:57 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-mdw17365-MDW
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1557846118.536860,VS0,VE6
Location: https://rubygems.org
```

**Comment by rsanheim** [comment]
My mistake, trying to mirror from rubyforge is wrong. I must have copied from a really old blog post somewhere.  Changing my mirrorrc to point at rubygems.org gets things going.
