### ISSUE TITLE
rubygems-mirror is incompatible with RubyGems 3.5+

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems-mirror#76]
As reported [here](https://lists.fedoraproject.org/archives/list/ruby-sig@lists.fedoraproject.org/message/V7M4LAQH5DU6CBEANNT5NGEL77HF4Q3V/), rubygems-mirror is incompatible with RubyGems 3.5 due to rubygems/rubygems#7085:

~~~
$ ruby -Ilib -e 'Dir.glob "./test/test_*.rb", &method(:require)'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- rubygems/indexer (LoadError)
    from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
    from /builddir/build/BUILD/rubygems-mirror-1.3.0/usr/share/gems/gems/rubygems-mirror-1.3.0/lib/rubygems/mirror/test_setup.rb:7:in `<top (required)>'
    from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
    from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
    from /builddir/build/BUILD/rubygems-mirror-1.3.0/usr/share/gems/gems/rubygems-mirror-1.3.0/test/test_gem_mirror.rb:3:in `<top (required)>'
    from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
    from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:127:in `require'
    from <internal:dir>:411:in `glob'
    from -e:1:in `<main>'
~~~

**Comment by voxik** [comment]
@pvalena FYI

**Comment by segiddins** [comment]
I believe it is only the tests that should be failing?

**Comment by voxik** [comment]
> I believe it is only the tests that should be failing?

Sorry, I have not investigated deeper. It looks so. OTOH it is coming from `lib` directory ...
